In [1]:
import pandas as pd
import numpy as np

In [20]:
df=pd.read_csv("https://github.com/Boykai/Project-4-White-Wine-Dataset/raw/master/wineQualityWhites.csv")
df

Unnamed: 0  fixed.acidity  volatile.acidity  citric.acid  \
0              1            7.0              0.27         0.36   
1              2            6.3              0.30         0.34   
2              3            8.1              0.28         0.40   
3              4            7.2              0.23         0.32   
4              5            7.2              0.23         0.32   
...          ...            ...               ...          ...   
4893        4894            6.2              0.21         0.29   
4894        4895            6.6              0.32         0.36   
4895        4896            6.5              0.24         0.19   
4896        4897            5.5              0.29         0.30   
4897        4898            6.0              0.21         0.38   

      residual.sugar  chlorides  free.sulfur.dioxide  total.sulfur.dioxide  \
0               20.7      0.045                 45.0                 170.0   
1                1.6      0.049                 14.0                 132.0   
2                6.9      0.050                 30.0                  97.0   
3                8.5      0.058                 47.0                 186.0   
4                8.5      0.058                 47.0                 186.0   
...              ...        ...                  ...                   ...   
4893             1.6      0.039                 24.0                  92.0   
4894             8.0      0.047                 57.0                 168.0   
4895             1.2      0.041                 30.0                 111.0   
4896             1.1      0.022                 20.0                 110.0   
4897             0.8      0.020                 22.0                  98.0   

      density    pH  sulphates  alcohol  quality  
0     1.00100  3.00       0.45      8.8        6  
1     0.99400  3.30       0.49      9.5        6  
2     0.99510  3.26       0.44     10.1        6  
3     0.99560  3.19       0.40      9.9        6  
4     0.99560  3.19       0.40      9.9        6  
...       ...   ...        ...      ...      ...  
4893  0.99114  3.27       0.50     11.2        6  
4894  0.99490  3.15       0.46      9.6        5  
4895  0.99254  2.99       0.46      9.4        6  
4896  0.98869  3.34       0.38     12.8        7  
4897  0.98941  3.26       0.32     11.8        6  

[4898 rows x 13 columns]

In [28]:
df.head()

Unnamed: 0  fixed.acidity  volatile.acidity  citric.acid  residual.sugar  \
0           1            7.0              0.27         0.36            20.7   
1           2            6.3              0.30         0.34             1.6   
2           3            8.1              0.28         0.40             6.9   
3           4            7.2              0.23         0.32             8.5   
4           5            7.2              0.23         0.32             8.5   

   chlorides  free.sulfur.dioxide  total.sulfur.dioxide  density    pH  \
0      0.045                 45.0                 170.0   1.0010  3.00   
1      0.049                 14.0                 132.0   0.9940  3.30   
2      0.050                 30.0                  97.0   0.9951  3.26   
3      0.058                 47.0                 186.0   0.9956  3.19   
4      0.058                 47.0                 186.0   0.9956  3.19   

   sulphates  alcohol  quality  
0       0.45      8.8        6  
1       0.49      9.5        6  
2       0.44     10.1        6  
3       0.40      9.9        6  
4       0.40      9.9        6

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4898 entries, 0 to 4897
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Unnamed: 0            4898 non-null   int64  
 1   fixed.acidity         4898 non-null   float64
 2   volatile.acidity      4898 non-null   float64
 3   citric.acid           4898 non-null   float64
 4   residual.sugar        4898 non-null   float64
 5   chlorides             4898 non-null   float64
 6   free.sulfur.dioxide   4898 non-null   float64
 7   total.sulfur.dioxide  4898 non-null   float64
 8   density               4898 non-null   float64
 9   pH                    4898 non-null   float64
 10  sulphates             4898 non-null   float64
 11  alcohol               4898 non-null   float64
 12  quality               4898 non-null   int64  
dtypes: float64(11), int64(2)
memory usage: 497.6 KB


In [30]:
df.describe()

Unnamed: 0  fixed.acidity  volatile.acidity  citric.acid  \
count  4898.000000    4898.000000       4898.000000  4898.000000   
mean   2449.500000       6.854788          0.278241     0.334192   
std    1414.075139       0.843868          0.100795     0.121020   
min       1.000000       3.800000          0.080000     0.000000   
25%    1225.250000       6.300000          0.210000     0.270000   
50%    2449.500000       6.800000          0.260000     0.320000   
75%    3673.750000       7.300000          0.320000     0.390000   
max    4898.000000      14.200000          1.100000     1.660000   

       residual.sugar    chlorides  free.sulfur.dioxide  total.sulfur.dioxide  \
count     4898.000000  4898.000000          4898.000000           4898.000000   
mean         6.391415     0.045772            35.308085            138.360657   
std          5.072058     0.021848            17.007137             42.498065   
min          0.600000     0.009000             2.000000              9.000000   
25%          1.700000     0.036000            23.000000            108.000000   
50%          5.200000     0.043000            34.000000            134.000000   
75%          9.900000     0.050000            46.000000            167.000000   
max         65.800000     0.346000           289.000000            440.000000   

           density           pH    sulphates      alcohol      quality  
count  4898.000000  4898.000000  4898.000000  4898.000000  4898.000000  
mean      0.994027     3.188267     0.489847    10.514267     5.877909  
std       0.002991     0.151001     0.114126     1.230621     0.885639  
min       0.987110     2.720000     0.220000     8.000000     3.000000  
25%       0.991723     3.090000     0.410000     9.500000     5.000000  
50%       0.993740     3.180000     0.470000    10.400000     6.000000  
75%       0.996100     3.280000     0.550000    11.400000     6.000000  
max       1.038980     3.820000     1.080000    14.200000     9.000000

In [31]:
df.columns

Index(['Unnamed: 0', 'fixed.acidity', 'volatile.acidity', 'citric.acid',
       'residual.sugar', 'chlorides', 'free.sulfur.dioxide',
       'total.sulfur.dioxide', 'density', 'pH', 'sulphates', 'alcohol',
       'quality'],
      dtype='object')

In [32]:
df.shape

(4898, 13)

In [33]:
df['quality'].value_counts()

6    2198
5    1457
7     880
8     175
4     163
3      20
9       5
Name: quality, dtype: int64

In [34]:
df.groupby('quality').mean()

Unnamed: 0  fixed.acidity  volatile.acidity  citric.acid  \
quality                                                              
3        1885.250000       7.600000          0.333250     0.336000   
4        2172.288344       7.129448          0.381227     0.304233   
5        2339.716541       6.933974          0.302011     0.337653   
6        2559.686988       6.837671          0.260564     0.338025   
7        2456.294318       6.734716          0.262767     0.325625   
8        2310.045714       6.657143          0.277400     0.326514   
9         981.400000       7.420000          0.298000     0.386000   

         residual.sugar  chlorides  free.sulfur.dioxide  total.sulfur.dioxide  \
quality                                                                         
3              6.392500   0.054300            53.325000            170.600000   
4              4.628221   0.050098            23.358896            125.279141   
5              7.334969   0.051546            36.432052            150.904598   
6              6.441606   0.045217            35.650591            137.047316   
7              5.186477   0.038191            34.125568            125.114773   
8              5.671429   0.038314            36.720000            126.165714   
9              4.120000   0.027400            33.400000            116.000000   

          density        pH  sulphates    alcohol  
quality                                            
3        0.994884  3.187500   0.474500  10.345000  
4        0.994277  3.182883   0.476135  10.152454  
5        0.995263  3.168833   0.482203   9.808840  
6        0.993961  3.188599   0.491106  10.575372  
7        0.992452  3.213898   0.503102  11.367936  
8        0.992236  3.218686   0.486229  11.636000  
9        0.991460  3.308000   0.466000  12.180000

In [35]:
y=df['quality']

In [36]:
y.shape

(4898,)

In [37]:
y

0       6
1       6
2       6
3       6
4       6
       ..
4893    6
4894    5
4895    6
4896    7
4897    6
Name: quality, Length: 4898, dtype: int64

In [38]:
X=df.drop(['quality'],axis=1)

In [39]:
X.shape


(4898, 12)

In [40]:
X

Unnamed: 0  fixed.acidity  volatile.acidity  citric.acid  \
0              1            7.0              0.27         0.36   
1              2            6.3              0.30         0.34   
2              3            8.1              0.28         0.40   
3              4            7.2              0.23         0.32   
4              5            7.2              0.23         0.32   
...          ...            ...               ...          ...   
4893        4894            6.2              0.21         0.29   
4894        4895            6.6              0.32         0.36   
4895        4896            6.5              0.24         0.19   
4896        4897            5.5              0.29         0.30   
4897        4898            6.0              0.21         0.38   

      residual.sugar  chlorides  free.sulfur.dioxide  total.sulfur.dioxide  \
0               20.7      0.045                 45.0                 170.0   
1                1.6      0.049                 14.0                 132.0   
2                6.9      0.050                 30.0                  97.0   
3                8.5      0.058                 47.0                 186.0   
4                8.5      0.058                 47.0                 186.0   
...              ...        ...                  ...                   ...   
4893             1.6      0.039                 24.0                  92.0   
4894             8.0      0.047                 57.0                 168.0   
4895             1.2      0.041                 30.0                 111.0   
4896             1.1      0.022                 20.0                 110.0   
4897             0.8      0.020                 22.0                  98.0   

      density    pH  sulphates  alcohol  
0     1.00100  3.00       0.45      8.8  
1     0.99400  3.30       0.49      9.5  
2     0.99510  3.26       0.44     10.1  
3     0.99560  3.19       0.40      9.9  
4     0.99560  3.19       0.40      9.9  
...       ...   ...        ...      ...  
4893  0.99114  3.27       0.50     11.2  
4894  0.99490  3.15       0.46      9.6  
4895  0.99254  2.99       0.46      9.4  
4896  0.98869  3.34       0.38     12.8  
4897  0.98941  3.26       0.32     11.8  

[4898 rows x 12 columns]

In [41]:
from sklearn.preprocessing import StandardScaler


In [42]:
sc=StandardScaler()

In [43]:
X=sc.fit_transform(X)

In [44]:
X

array([[-1.73169722e+00,  1.72096961e-01, -8.17699008e-02, ...,
        -1.24692128e+00, -3.49184257e-01, -1.39315246e+00],
       [-1.73098997e+00, -6.57501128e-01,  2.15895632e-01, ...,
         7.40028640e-01,  1.34184656e-03, -8.24275678e-01],
       [-1.73028272e+00,  1.47575110e+00,  1.74519434e-02, ...,
         4.75101984e-01, -4.36815783e-01, -3.36667007e-01],
       ...,
       [ 1.73028272e+00, -4.20473102e-01, -3.79435433e-01, ...,
        -1.31315295e+00, -2.61552731e-01, -9.05543789e-01],
       [ 1.73098997e+00, -1.60561323e+00,  1.16673788e-01, ...,
         1.00495530e+00, -9.62604939e-01,  1.85757201e+00],
       [ 1.73169722e+00, -1.01304317e+00, -6.77100966e-01, ...,
         4.75101984e-01, -1.48839409e+00,  1.04489089e+00]])

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
 X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,stratify=y, random_state=2529)

In [47]:
 X_train.shape, X_test.shape, y_train.shape, y_test.shape

((3428, 12), (1470, 12), (3428,), (1470,))

In [48]:
from sklearn.svm import SVC

In [49]:
svc=SVC()

In [51]:
svc.fit(X_train,y_train)

SVC()

In [52]:
y_pred=svc.predict(X_test)

In [53]:
y_pred.shape

(1470,)

In [54]:
y_pred

array([5, 7, 5, ..., 5, 5, 5], dtype=int64)

In [55]:
from sklearn.metrics import confusion_matrix,classification_report

In [56]:
print(confusion_matrix(y_test,y_pred))

[[  0   0   2   4   0   0   0]
 [  0   2  24  22   1   0   0]
 [  0   2 281 152   2   0   0]
 [  0   0 123 500  37   0   0]
 [  0   0   7 171  86   0   0]
 [  0   0   1  34  18   0   0]
 [  0   0   0   0   1   0   0]]


In [58]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         6
           4       0.50      0.04      0.08        49
           5       0.64      0.64      0.64       437
           6       0.57      0.76      0.65       660
           7       0.59      0.33      0.42       264
           8       0.00      0.00      0.00        53
           9       0.00      0.00      0.00         1

    accuracy                           0.59      1470
   macro avg       0.33      0.25      0.26      1470
weighted avg       0.57      0.59      0.56      1470



C:\Users\ROHTIH\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ROHTIH\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ROHTIH\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [60]:
y=df['quality'].apply(lambda y_value: 1 if y_value>=6 else 0)

In [61]:
y.value_counts()

1    3258
0    1640
Name: quality, dtype: int64

In [62]:
from sklearn.model_selection import train_test_split

In [63]:
 X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,stratify=y, random_state=2529)

In [64]:
 X_train.shape, X_test.shape, y_train.shape, y_test.shape

((3428, 12), (1470, 12), (3428,), (1470,))

In [65]:
from sklearn.svm import SVC

In [66]:
svc=SVC()

In [67]:
svc.fit(X_train,y_train)

SVC()

In [68]:
y_pred=svc.predict(X_test)

In [69]:
y_pred.shape

(1470,)

In [70]:
y_pred

array([0, 1, 1, ..., 1, 1, 1], dtype=int64)

In [71]:
from sklearn.metrics import confusion_matrix,classification_report

In [72]:
print(confusion_matrix(y_test,y_pred))

[[289 203]
 [113 865]]


In [73]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.72      0.59      0.65       492
           1       0.81      0.88      0.85       978

    accuracy                           0.79      1470
   macro avg       0.76      0.74      0.75      1470
weighted avg       0.78      0.79      0.78      1470



In [74]:
df_new=df.sample(1)

In [75]:
df_new

Unnamed: 0  fixed.acidity  volatile.acidity  citric.acid  \
2911        2912            6.2              0.36         0.14   

      residual.sugar  chlorides  free.sulfur.dioxide  total.sulfur.dioxide  \
2911             8.9      0.036                 38.0                 155.0   

      density    pH  sulphates  alcohol  quality  
2911  0.99622  3.27        0.5      9.4        5

In [76]:
df_new.shape

(1, 13)

In [77]:
X_new=df_new.drop(['quality'],axis=1)

In [78]:
X_new=sc.fit_transform(X_new)

In [79]:
y_pred_new=svc.predict(X_new)

In [80]:
y_pred_new

array([1], dtype=int64)